### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by JonnyTurnerUK** [owldesign/focuspoint#1]
Hello, we're getting a missing image icon when we try to use focuspoint with assets in Craft CMS (2.6.2776). I've been over and over the instructions but can't seem to get this sorted. Have you seen this before? I'm sure it's something really easy that we've missed.

![screen shot 2016-03-22 at 11 58 50](https://cloud.githubusercontent.com/assets/654547/13950961/e737b326-f025-11e5-9d0a-3a54568a25e5.png)

**Comment by owldesign** [comment]
@JonnyTurnerUK  hard to tell from just image, do you get any errors in your console log? or at `storage/runtime/logs.craft.log`?

Whats your asset source (local, s3, rackspace)? 
When you upload an image are you able to view the asset by hitting `View asset`? ![screenshot](https://cloud.githubusercontent.com/assets/438764/13968566/aceefe58-f03a-11e5-921d-9a308582d7e9.png)

**Comment by owldesign** [comment]
Actually I might know what the problem is.. In code I have an Image Transform set to `medium` which you most likely don't have. That was for my photos (i was uploading large files) and I should have removed that from final code..

Pull master and see if image shows up.
